{{- if .Values.lightlytics.lightlytics_containers.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lightlytics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "lightlytics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.lightlytics.replicas }}
  selector:
    matchLabels:
  {{- include "lightlytics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "lightlytics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "lightlytics.serviceAccountName" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      tolerations:
          {{- toYaml .Values.lightlytics.tolerations | nindent 8 }}
      {{- with .Values.lightlytics.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      {{- range $container_name, $container_values := .Values.lightlytics.lightlytics_containers.containers }}
      {{- if $container_values.enabled }}
        - name: {{ $container_name }}
          image: {{ template "lightlytics.image-path" $}}
          imagePullPolicy: {{ $.Values.lightlytics.image.pullPolicy }}
          command:
            {{- range $container_values.command }}
            - {{ . }}
            {{- end }}
          resources:
            {{- toYaml $container_values.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
          readinessProbe:
            exec:
              command:
                - cat
                - /main.py
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - cat
                - /main.py
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: LIGHTLYTICS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "lightlytics.apiTokenSecretName" $ }}
                  key: api-key
            - name: LIGHTLYTICS_API_URL
              value: {{ $.Values.lightlytics.apiUrl | quote }}

            - name: ENABLE_POD_PROCESSES
              value: {{ $.Values.lightlytics.process_discovery_containers.enabled | quote }}

            - name: POD_PROCESSES_SERVICE
              value: {{ template "lightlytics.fullname" $}}-process-discovery

            - name: POD_PROCESSES_PORT
              value: "8080"

            - name: FULL_SCAN_SCHEDULE_SECONDS
              value: {{ $.Values.lightlytics.fullScanScheduleSeconds | quote }}

            - name: FILTER_RUNNING_PODS
              value: {{ $.Values.lightlytics.filterRunningPods | quote }}

            - name: FIELD_SELECTORS_NAMESPACES
              value: {{ $.Values.lightlytics.fieldSelectorsNamespaces | quote }}

            - name: FIELD_SELECTORS_NAMES
              value: {{ $.Values.lightlytics.fieldSelectorsNames | quote }}

            - name: IN_LABEL_SELECTOR
              value: {{ $.Values.lightlytics.inLabelSelector | quote }}

            - name: EXISTS_LABEL_SELECTOR
              value: {{ $.Values.lightlytics.existLabelSelector | quote }}

            - name: EQUALS_LABEL_SELECTOR
              value: {{ $.Values.lightlytics.equalsLabelSelector | quote }}

            - name: WORKFLOW
              value: {{ $.Values.lightlytics.workflow | quote }}

            - name: PORT
              value: {{ $.Values.lightlytics.port | quote }}

            {{- range $envVarName, $envVarValue := $.Values.lightlytics.env }}
            - name: {{ $envVarName }}
              value: {{ $envVarValue | quote }}
            {{- end }}
    {{- end }}
    {{- end }}
{{- end }}