{{- if .Values.stream-security.cost_containers.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "stream-security.fullname" . }}-cost
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "stream-security.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.stream-security.replicas }}
  selector:
    matchLabels:
  {{- include "stream-security.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "stream-security.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "stream-security.serviceAccountName" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000  
      tolerations:
          {{- toYaml .Values.stream-security.tolerations | nindent 8 }}
      containers:
      {{- range $container_name, $container_values := .Values.stream-security.cost_containers.containers }}
        - name: {{ $container_name }}
          image: {{ template "stream-security.cost-image-path" $}}
          imagePullPolicy: {{ $.Values.stream-security.cost_image.pullPolicy }}
          command:
            {{- range $container_values.command }}
            - {{ . }}
            {{- end }}
          resources:
            {{- toYaml $container_values.resources | nindent 12 }}
          securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                 drop:
                    - all
                 add:
                    - NET_BIND_SERVICE
          readinessProbe:
              exec:
                 command:
                   - cat
                   - /main.py
              initialDelaySeconds: 30
              periodSeconds: 30
          livenessProbe:
              exec:
                 command:
                   - cat
                   - /main.py
              initialDelaySeconds: 30
              periodSeconds: 30
          env:
            - name: STREAMSEC_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "stream-security.apiTokenSecretName" $ }}
                  key: api-key
            - name: STREAMSEC_API_URL
              value: {{ $.Values.stream-security.apiUrl | quote }}
            - name: PORT
              value: {{ $.Values.stream-security.port | quote }}
              
            {{- range $envVarName, $envVarValue := $.Values.stream-security.env }}
            - name: {{ $envVarName }}
              value: {{ $envVarValue | quote }}
            {{- end }}
    {{- end }}
{{- end }}