apiVersion: v2
name: streamsec-agent
description: Stream Security Agent Helm Chart
type: application
version: 1.1.14
appVersion: 1.1.4
dependencies:
- name: tetragon
  condition: streamsec.runtime_agent.enabled
  version: 1.3.0
  repository: https://helm.cilium.io
